builders:
  embedded_config:
    import: "package:embedded_config/builder.dart"
    builder_factories: ["configBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: root_package
  embedded_config_to_source:
    import: "package:embedded_config/builder.dart"
    builder_factories: ["configBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source
    auto_apply: none
