name: embedded_config
author: Ethan Lafrenais

publish_to: none

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.32.5
  build: ^0.12.7
  source_gen: ^0.9.1

dev_dependencies:
  build_runner: ^0.9.2
