name: embedded_config
author: Ethan Lafrenais

publish_to: none

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.32.0 <0.34.0'
  build: '>=0.12.0 <2.0.0'
  code_builder: ^3.1.0
  source_gen: ^0.9.0
