name: embedded_config_annotations
description: Annotations to configure code generation for the `embedded_config` package.
version: 0.2.0
homepage: https://github.com/Francessco121/dart-embedded-config

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
