builders:
  angular_embedded_config:
    import: "package:angular_embedded_config/builder.dart"
    builder_factories: ["configBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: root_package
    # This must run before Angular for the user to be able to
    # use build-time injection with the embedded config.
    runs_before:
      - "angular"

# Prevent embedded_config from running on its own since we are 
# forwarding ourselves to it already.
targets:
  $default:
    builders:
      embedded_config:
        enabled: false
