name: embedded_config
description: >
  Allows application configurations to be embedded directly into 
  source code at build-time, to solve the problem of needing
  different configurations per build environment.
version: 0.4.0
homepage: https://github.com/Francessco121/dart-embedded-config

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: '>=2.0.0 <4.0.0'
  build: ^2.0.0
  code_builder: ^4.0.0
  embedded_config_annotations: '>=0.3.0 <0.4.0'
  source_gen: ^1.0.0

dev_dependencies:
  build_test: ^2.1.0
  collection: ^1.15.0
  lints: ^1.0.1
  test: ^1.20.0

dependency_overrides:
  embedded_config_annotations:
    path: ../embedded_config_annotations
