name: embedded_config

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.32.0 <0.39.0'
  build: '>=0.12.0 <2.0.0'
  code_builder: ^3.2.0
  embedded_config_annotations:
    git: 
      url: https://github.com/Francessco121/dart-embedded-config.git
      path: embedded_config_annotations
  source_gen: ^0.9.0

dependency_overrides:
  embedded_config_annotations:
    path: ../embedded_config_annotations
