name: embedded_config
description: >
  A package which allows application configurations to be embedded directly 
  into source code at build-time. Configuration can come from JSON files, 
  environment variables, and build.yaml files.
version: 0.1.0
homepage: https://github.com/Francessco121/dart-embedded-config

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.32.0 <0.39.0'
  build: '>=0.12.0 <2.0.0'
  code_builder: ^3.2.0
  embedded_config_annotations:
    git: 
      url: https://github.com/Francessco121/dart-embedded-config.git
      path: embedded_config_annotations
  source_gen: ^0.9.0

dependency_overrides:
  embedded_config_annotations:
    path: ../embedded_config_annotations
