name: embedded_config
description: >
  Allows application configurations to be embedded directly into
  source code at build-time, to solve the problem of needing
  different configurations per build environment.
version: 0.5.0
homepage: https://github.com/Francessco121/dart-embedded-config
topics:
  - config

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  analyzer: '>=5.12.0 <7.0.0'
  build: ^2.0.0
  code_builder: ^4.0.0
  embedded_config_annotations: '>=0.3.0 <0.4.0'
  source_gen: ^1.2.0
  yaml: ^3.1.2

dev_dependencies:
  build_test: ^2.1.0
  collection: ^1.17.0
  lints: ^2.0.1
  path: ^1.8.3
  test: ^1.23.1

dependency_overrides:
  embedded_config_annotations:
    path: ../embedded_config_annotations
