name: embedded_config
description: >
  Allows application configs to be embedded directly into source 
  code at build-time. Configuration can come from JSON files, 
  environment variables, and build.yaml files.
version: 0.1.2
homepage: https://github.com/Francessco121/dart-embedded-config

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.32.4 <0.40.0'
  build: ^1.0.0
  code_builder: ^3.2.0
  embedded_config_annotations: '>=0.1.0 <0.2.0'
  source_gen: ^0.9.0

dev_dependencies:
  pedantic: ^1.9.0
